version: "3.8"

services:
    loadbalancer:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - lemoo_network
        deploy:
            replicas: 1
        restart: always

networks:
    lemoo_network:
        driver: overlay
