name: Build and Push Docker Image

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout source code
            - name: Checkout code
              uses: actions/checkout@v4
            # Build Docker image
            - name: Build Docker image
              run: |
                  docker build -t zeustakeshi/lemoo-pos:latest .
            - name: login Dockerhub
              run: |
                docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push zeustakeshi/lemoo-pos:latest
